#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xF893C674816AA95D (filipe@lains.me)
#
Name     : build
Version  : 0.6.0.post1
Release  : 3
URL      : https://files.pythonhosted.org/packages/d1/18/0ce502d693c73d25a2d8a2205f80c0f7a13f80edf023ad68b067e97dbafa/build-0.6.0.post1.tar.gz
Source0  : https://files.pythonhosted.org/packages/d1/18/0ce502d693c73d25a2d8a2205f80c0f7a13f80edf023ad68b067e97dbafa/build-0.6.0.post1.tar.gz
Source1  : https://files.pythonhosted.org/packages/d1/18/0ce502d693c73d25a2d8a2205f80c0f7a13f80edf023ad68b067e97dbafa/build-0.6.0.post1.tar.gz.asc
Summary  : A simple, correct PEP517 package builder
Group    : Development/Tools
License  : MIT
Requires: build-bin = %{version}-%{release}
Requires: build-license = %{version}-%{release}
Requires: build-python = %{version}-%{release}
Requires: build-python3 = %{version}-%{release}
Requires: packaging
Requires: pep517
Requires: tomli
BuildRequires : buildreq-distutils3
BuildRequires : packaging
BuildRequires : pep517
BuildRequires : tomli

%description
# build
[![CI check](https://github.com/pypa/build/workflows/check/badge.svg)](https://github.com/pypa/build/actions)
[![CI test](https://github.com/pypa/build/actions/workflows/test.yml/badge.svg)](https://github.com/pypa/build/actions/workflows/test.yml)
[![codecov](https://codecov.io/gh/pypa/build/branch/main/graph/badge.svg)](https://codecov.io/gh/pypa/build)
[![Documentation Status](https://readthedocs.org/projects/pypa-build/badge/?version=latest)](https://pypa-build.readthedocs.io/en/latest/?badge=latest)
[![PyPI version](https://badge.fury.io/py/build.svg)](https://pypi.org/project/build/)
[![Discord](https://img.shields.io/discord/803025117553754132?label=Discord%20chat%20%23build&style=flat-square)](https://discord.gg/pypa)

%package bin
Summary: bin components for the build package.
Group: Binaries
Requires: build-license = %{version}-%{release}

%description bin
bin components for the build package.


%package license
Summary: license components for the build package.
Group: Default

%description license
license components for the build package.


%package python
Summary: python components for the build package.
Group: Default
Requires: build-python3 = %{version}-%{release}

%description python
python components for the build package.


%package python3
Summary: python3 components for the build package.
Group: Default
Requires: python3-core
Provides: pypi(build)
Requires: pypi(packaging)
Requires: pypi(pep517)
Requires: pypi(tomli)

%description python3
python3 components for the build package.


%prep
%setup -q -n build-0.6.0.post1
cd %{_builddir}/build-0.6.0.post1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1628206573
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/build
cp %{_builddir}/build-0.6.0.post1/LICENSE %{buildroot}/usr/share/package-licenses/build/4339a5c41946d5ce6e23a8b8c4fff00d838d40c9
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyproject-build

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/build/4339a5c41946d5ce6e23a8b8c4fff00d838d40c9

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
